### ISSUE TITLE
Текстовый комментарий у закладки

### ISSUE THREAD

**Issue by and-se** [Svjatoslav-so/FaceRecognition-NmBook#1]
Нужна возможность снабжать закладку текстовым комментарием. Он должен быть виден при просмотре закладки на экране закладок. Видимость комментария в остальных контекстах - как получится.

**Comment by Svjatoslav-so** [comment]
Реализованы комментарии к закладкам (коммит: 16433b6fdcdbcbbd910dce20443ec9eb58f14da0)
