### ISSUE TITLE
Инструкция по установке и использованию

### ISSUE THREAD

**Issue by and-se** [Svjatoslav-so/FaceRecognition-NmBook#2]
Инструкции по установке и использованию надо добавить в репозиторий с исходниками либо в раздел Wiki (это отдельный независимый репозиторий).

Желательно не выкладывать имеющиеся бинарные файлы (pdf или docx), а оформить информацию в виде Markdown (*.md), а картинки положить в отдельную папку в репозитории.

**Comment by Svjatoslav-so** [comment]
Реализовано в коммите 785f052d68739aa7aef4c2d3a927d98287130a69
